<form>
	<a href="controllers/signup.php" data-role="button" class="blue-btn" data-theme="g">Sign Up!</a>
	<a href="controllers/auth.php" data-role="button" class="blue-btn" data-theme="g">Log In!</a>
	
	<a href="controllers/newTask.php" data-role="button" class="blue-btn" data-theme="g">Add Task</a>
	<a href="controllers/taskDetails.php" data-role="button" class="blue-btn" data-theme="g">My Tasks</a>
</form>