<!DOCTYPE html> 
<html> 
<head> 
	<title><?php echo $pageTitle?></title> 
	
	<meta name="viewport" content="width=device-width, initial-scale=1"> 

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
	<link rel="stylesheet" href="css/main-style.css" />
	<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>
</head> 

<body>
	
	<div data-role="page" id="index" data-theme="g">
    <div data-role="header">
    <a href="../index.php" data-role="button" data-icon="home" data-iconpos="notext" data-inline="true" id="homeIcon">Home</a>
    
   <h1> Welcome to Wind Up!</h1></div>
   <div data-role="content">
    <img src="assets/winduplogo.png" alt="Wind up App logo" />