
<div data-role="page" id="newTask">
<h1>new task</h1>

<form action="?" method="POST">
<label data-role="label" for="taskTitle">Title:</label>
	<input data-role="input" type="text" name="title" id="title" maxlength="50" size="50"/><br/> <br/>
<label data-role="label" for="task">Task</label>
	<input data-role="input"type="text" name="task" id="task" maxlength="350" size="350"/><br/><br/>
<label data-role="label" for="taskType">Type</label>
	<input data-role="input" type="text" name="username" id="username" maxlength="20" size="20"/>
	
	<input data-role="button" type="button" name="newTask" class="gold-btn"/>
</form>

</div>