<h1>Sign Up!</h1>

<form action="" method="POST">
<label for="username">Username:</label>
	<input type="text" name="fullname" id="fullname" maxlength="20" size="20"/><br/> <br/>
<label for="username">Name:</label>
	<input type="text" name="lastname" id="lastname" maxlength="20" size="20"/><br/> <br/>
<label for="username">Username:</label>
	<input type="text" name="username" id="username" maxlength="20" size="20"/><br/> <br/>
<label for="password">Password:</label>
	<input type="password" name="password" id="password" maxlength="20" size="20"/>
</form>
