
<div data-role="page" data-theme="f">

<div data-role="header"><h1>Sign Up</h1></div>

<div data-role="content">
	<form action="?" method="POST">
	<label>Name<br/>
		<input type="text" name="fullname" id="name" maxlength="20"/>
	</label>	
	<label>Last Name<br/>
		<input type="text" name="lastname" id="lastname" maxlength="20"/>
	</label>
	<label>username<br/>
		<input type="text" name="username" id="username" maxlength="20"/>
	</label>
	<label>Password<br/>
		<input type="password" name="password" id="password" maxlength="20"/>
	</label><br/><br/>
	<input type="submit" data-role="submit" data-theme="g" size="30"/>
	</form>
</div>

</div>